const SOUPKITCHENS = [
    {
     name: "Boston Soup Kitchen",
     location: "720 Harrison Ave, Boston, MA 02118",
     weekdayHours: "9:00 AM - 5:00 PM",
     weekendHours: "10:00 AM - 3:00 PM",
     currentStatus: true,
     glutenFree: true,
     kosher: false,
     halal: true,
     vegan: true,
     lactoseIntolerant: true,
     headCount: 30,
     totalCapacity: 100,
     waitTime: "15 minutes",
     staffAvailability: 5,
     volunteerOpenings: 3,
     skillsNeeded: "Cooking, Serving",
   },
    {
     name: "Harbor Light Soup House",
     location: "23 Court St, Boston, MA 02108",
     weekdayHours: "8:00 AM - 6:00 PM",
     weekendHours: "9:00 AM - 4:00 PM",
     currentStatus: true,
     glutenFree: false,
     kosher: true,
     halal: false,
     vegan: true,
     lactoseIntolerant: false,
     headCount: 40,
     totalCapacity: 120,
     waitTime: "20 minutes",
     staffAvailability: 6,
     volunteerOpenings: 2,
     skillsNeeded: "Serving, Cleaning",
   },
{
     name: "Beacon Hill Food Stop",
     location: "145 Bowdoin St, Boston, MA 02108",
     weekdayHours: "10:00 AM - 7:00 PM",
     weekendHours: "11:00 AM - 4:00 PM",
     currentStatus: true,
     glutenFree: true,
     kosher: false,
     halal: true,
     vegan: false,
     lactoseIntolerant: true,
     headCount: 25,
     totalCapacity: 110,
     waitTime: "10 minutes",
     staffAvailability: 7,
     volunteerOpenings: 4,
     skillsNeeded: "Cooking, Cleaning, Serving",
   },
  {
     name: "Fenway Community Kitchen",
     location: "1282 Boylston St, Boston, MA 02215",
     weekdayHours: "9:00 AM - 6:00 PM",
     weekendHours: "10:00 AM - 5:00 PM",
     currentStatus: false,
     glutenFree: true,
     kosher: false,
     halal: false,
     vegan: true,
     lactoseIntolerant: false,
     headCount: 35,
     totalCapacity: 130,
     waitTime: "30 minutes",
     staffAvailability: 8,
     volunteerOpenings: 3,
     skillsNeeded: "Serving, Cleaning",
   },
   {
     name: "North End Nourish",
     location: "11 Thacher St, Boston, MA 02113",
     weekdayHours: "9:30 AM - 5:30 PM",
     weekendHours: "11:00 AM - 4:30 PM",
     currentStatus: true,
     glutenFree: false,
     kosher: true,
     halal: true,
     vegan: true,
     lactoseIntolerant: true,
     headCount: 28,
     totalCapacity: 115,
     waitTime: "20 minutes",
     staffAvailability: 6,
     volunteerOpenings: 2,
     skillsNeeded: "Cooking, Serving, Management",
   },
   {
     name: "Back Bay Buffet",
     location: "353 Newbury St, Boston, MA 02115",
     weekdayHours: "8:30 AM - 7:00 PM",
     weekendHours: "10:00 AM - 5:00 PM",
     currentStatus: false,
     glutenFree: true,
     kosher: true,
     halal: false,
     vegan: false,
     lactoseIntolerant: false,
     headCount: 40,
     totalCapacity: 120,
     waitTime: "25 minutes",
     staffAvailability: 7,
     volunteerOpenings: 4,
     skillsNeeded: "Cooking, Serving, Cashiering",
   },
  {
     name: "Dorchester Dine House",
     location: "785 Washington St, Boston, MA 02124",
     weekdayHours: "9:00 AM - 6:00 PM",
     weekendHours: "10:30 AM - 4:00 PM",
     currentStatus: true,
     glutenFree: false,
     kosher: false,
     halal: true,
     vegan: true,
     lactoseIntolerant: true,
     headCount: 38,
     totalCapacity: 125,
     waitTime: "18 minutes",
     staffAvailability: 8,
     volunteerOpenings: 3,
     skillsNeeded: "Cooking, Serving, Cleaning",
   },
    {
     name: "Charlestown Chow Time",
     location: "55 Monument Ave, Boston, MA 02129",
     weekdayHours: "8:30 AM - 6:30 PM",
     weekendHours: "10:00 AM - 4:30 PM",
     currentStatus: true,
     glutenFree: true,
     kosher: true,
     halal: false,
     vegan: false,
     lactoseIntolerant: true,
     headCount: 42,
     totalCapacity: 130,
     waitTime: "22 minutes",
     staffAvailability: 9,
     volunteerOpenings: 2,
     skillsNeeded: "Cooking, Serving, Management",
   },
    {
     name: "Roxbury Food Retreat",
     location: "220 Warren St, Boston, MA 02119",
     weekdayHours: "9:00 AM - 7:00 PM",
     weekendHours: "11:00 AM - 5:00 PM",
     currentStatus: false,
     glutenFree: true,
     kosher: false,
     halal: true,
     vegan: true,
     lactoseIntolerant: false,
     headCount: 36,
     totalCapacity: 110,
     waitTime: "20 minutes",
     staffAvailability: 7,
     volunteerOpenings: 4,
     skillsNeeded: "Cooking, Serving, Cleaning",
    },
   {
     name: "South End Soup Station",
     location: "540 Tremont St, Boston, MA 02116",
     weekdayHours: "8:00 AM - 6:00 PM",
     weekendHours: "10:30 AM - 4:00 PM",
     currentStatus: true,
     glutenFree: false,
     kosher: true,
     halal: true,
     vegan: false,
     lactoseIntolerant: true,
     headCount: 33,
     totalCapacity: 120,
     waitTime: "18 minutes",
     staffAvailability: 8,
     volunteerOpenings: 3,
     skillsNeeded: "Cooking, Serving, Management",
   }
];